say: propertyConditional
my:
  property1: propvalue1
  property2: propvalue2

logging:
  config: classpath:logging/logback.xml
#  level:
#    org.springframework.web: INFO
#    org.hibernate: ERROR
#    ru.inbox.savinov_vu.logging: DEBUG
#  path: ./log/app.log

spring:
  datasource:
    url: jdbc:hsqldb:mem:bd
    username: sa
    password:
    driver-class-name: org.hsqldb.jdbcDriver
    schema: classpath:database/create-db.sql
    data: classpath:database/seed-data.sql

mybatis:
  type-aliases-package: ru.inbox.savinov_vu.utils.domain
#  mapper-locations: classpath*:/mappers/*.xml path to xml config
